version: "3"
services:
  portfolio:
    build:
      context: .
      dockerfile: ./portfolio/Dockerfile
    volumes:
      - ./portfolio:/home/app
      - ./apache_portfolio/ports.conf:/etc/apache2/ports.conf
      - ./ssls/letsencrypt/live/portfolio:/home/ssl
    entrypoint: ["/wait.sh"]
    depends_on: #links:
      - portfolio_db
    ports:
      - "80:80"
      - "443:443"
    restart:  always
  portfolio_db:
    image: postgres
    volumes:
      - ./portfolio/portfolio_db/data_portfolio/db:/var/lib/postgresql/data
    command: -p 5233
    env_file:
      - ./portfolio/.env
    restart:  always