# Generated by Django 3.2.6 on 2021-11-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
