# Generated by Django 3.2.6 on 2021-11-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_landing', '0002_aboutme_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='github_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='insta_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='linked_in_link',
            field=models.TextField(blank=True),
        ),
    ]
