# Generated by Django 3.2.6 on 2021-11-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_landing', '0003_auto_20211128_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='insta_link',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='linked_in_link',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='presentation',
        ),
        migrations.AddField(
            model_name='intro',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intro',
            name='github_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intro',
            name='insta_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intro',
            name='linked_in_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intro',
            name='presentation',
            field=models.TextField(blank=True),
        ),
    ]
