# Generated by Django 3.2.6 on 2021-11-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_landing', '0004_auto_20211128_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='description',
        ),
    ]
