# Generated by Django 3.2.6 on 2021-11-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_landing', '0005_remove_intro_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='aboutmetitle',
            field=models.TextField(blank=True),
        ),
    ]
