# Generated by Django 3.2.6 on 2021-11-29 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_landing', '0006_aboutme_aboutmetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ordering',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='ordering'),
        ),
        migrations.AddField(
            model_name='work',
            name='ordering',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='ordering'),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='lang_percent'),
        ),
    ]
