# Generated by Django 3.2.6 on 2021-11-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_landing', '0007_auto_20211129_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatesettings',
            name='sms_logging',
            field=models.BooleanField(default=False, verbose_name='Sms logging'),
        ),
    ]
