# Generated by Django 3.2.6 on 2021-11-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_landing', '0008_privatesettings_sms_logging'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='ordering',
            new_name='ordering_rate',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='ordering',
            new_name='ordering_rate',
        ),
    ]
