# Generated by Django 3.2.6 on 2021-11-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_landing', '0009_auto_20211129_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cvdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mycvname', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('cvmail', models.CharField(max_length=100)),
                ('cvlocation', models.CharField(max_length=100)),
                ('cvlinkedin', models.CharField(max_length=100)),
                ('cvwebsite', models.CharField(max_length=300)),
                ('myprofile', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('meta_desc', models.CharField(blank=True, max_length=160)),
                ('meta_keys', models.CharField(blank=True, max_length=300)),
                ('my_cv_photo', models.ImageField(blank=True, upload_to='photos/<django.db.models.fields.CharField>', verbose_name='Img')),
            ],
            options={
                'ordering': ['-mycvname'],
            },
        ),
    ]
