# Generated by Django 3.2.6 on 2021-11-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_landing', '0010_cvdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=200)),
                ('establishment', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('meta_desc', models.CharField(blank=True, max_length=160)),
                ('meta_keys', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'ordering': ['-years'],
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
