# Generated by Django 3.2.6 on 2021-11-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_landing', '0012_auto_20211130_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='page_lang',
            field=models.CharField(choices=[('ENG', 'ENG'), ('FR', 'FR'), ('RUS', 'RUS'), ('IT', 'IT')], default='ENG', max_length=10, verbose_name='LANGUAGE:'),
        ),
        migrations.AlterField(
            model_name='cvdata',
            name='page_lang',
            field=models.CharField(choices=[('ENG', 'ENG'), ('FR', 'FR'), ('RUS', 'RUS'), ('IT', 'IT')], default='ENG', max_length=10, verbose_name='LANGUAGE:'),
        ),
        migrations.AlterField(
            model_name='education',
            name='page_lang',
            field=models.CharField(choices=[('ENG', 'ENG'), ('FR', 'FR'), ('RUS', 'RUS'), ('IT', 'IT')], default='ENG', max_length=10, verbose_name='LANGUAGE:'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='page_lang',
            field=models.CharField(choices=[('ENG', 'ENG'), ('FR', 'FR'), ('RUS', 'RUS'), ('IT', 'IT')], default='ENG', max_length=10, verbose_name='LANGUAGE:'),
        ),
        migrations.AlterField(
            model_name='interests',
            name='page_lang',
            field=models.CharField(choices=[('ENG', 'ENG'), ('FR', 'FR'), ('RUS', 'RUS'), ('IT', 'IT')], default='ENG', max_length=10, verbose_name='LANGUAGE:'),
        ),
        migrations.AlterField(
            model_name='language',
            name='page_lang',
            field=models.CharField(choices=[('ENG', 'ENG'), ('FR', 'FR'), ('RUS', 'RUS'), ('IT', 'IT')], default='ENG', max_length=10, verbose_name='LANGUAGE:'),
        ),
        migrations.AlterField(
            model_name='service',
            name='page_lang',
            field=models.CharField(choices=[('ENG', 'ENG'), ('FR', 'FR'), ('RUS', 'RUS'), ('IT', 'IT')], default='ENG', max_length=10, verbose_name='LANGUAGE:'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='page_lang',
            field=models.CharField(choices=[('ENG', 'ENG'), ('FR', 'FR'), ('RUS', 'RUS'), ('IT', 'IT')], default='ENG', max_length=10, verbose_name='LANGUAGE:'),
        ),
        migrations.AlterField(
            model_name='work',
            name='page_lang',
            field=models.CharField(choices=[('ENG', 'ENG'), ('FR', 'FR'), ('RUS', 'RUS'), ('IT', 'IT')], default='ENG', max_length=10, verbose_name='LANGUAGE:'),
        ),
    ]
