# Generated by Django 3.2.6 on 2021-11-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_landing', '0013_auto_20211130_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_link',
            field=models.TextField(blank=True),
        ),
    ]
