# Generated by Django 3.2.6 on 2021-12-02 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_landing', '0014_work_work_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='ordering_rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='ordering'),
        ),
    ]
