# Generated by Django 3.2.6 on 2022-01-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_landing', '0015_experience_ordering_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_lang', models.CharField(choices=[('ENG', 'ENG'), ('FR', 'FR'), ('RUS', 'RUS'), ('IT', 'IT')], default='ENG', max_length=10, verbose_name='LANGUAGE:')),
                ('certificate_name', models.CharField(max_length=200)),
                ('date_obtained', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('certificate_link', models.TextField(blank=True)),
                ('certificate_photo', models.ImageField(blank=True, upload_to='photos/<django.db.models.fields.CharField>', verbose_name='Img')),
            ],
        ),
    ]
